Go back to streaming wget

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -34,22 +34,19 @@ jobs:
           while [ "${ENDPOINT}" ]
           do
             ENDPOINT="$(curl -sS "${ENDPOINT}" | tee "${TMP_FILE}" | jq --raw-output "${JQ_QUERY}")"
-            cat "${TMP_FILE}" | \
+            cat "${TMP_FILE}"
+          done | \
               jq --slurp '[.[].results[]]' | \
               tee "index.json" | \
               jq --raw-output '.[].formats[]' | \
-              xargs --max-procs="$(nproc)" -IURL \
-                sh -c "${WGET_CMD}"
-          done
+              xargs --max-procs="$(nproc)" -IURL sh -c "${WGET_CMD}"
         env:
           ENDPOINT: 'https://gutendex.com/books/?languages=eo'
           JQ_QUERY: '.next|tostring|sub("^null$"; ""; "i")'
           TMP_FILE: '${{ runner.temp }}/results'
           WAIT_SEC: 10
           WGET_CMD: |
-            wget --no-verbose --execute robots=off --random-wait --wait "${WAIT_SEC}" --no-host-directories --force-directories URL || {
-              echo "::error title=WGET ERROR CODE $?::URL" ;
-            }
+            wget --no-verbose --execute robots=off --random-wait --wait "${WAIT_SEC}" --no-host-directories --force-directories URL || echo "::error title=WGET ERROR CODE ${?}::URL"
 
       - name: "Add files"
         run: git add . 
